system:
  # 添加新好友或群之后通知给指定的人
  newFriendNotify:
    enable: false
    toUser:
      - "wxid_xxxxx"
  # 默认AI等配置
  defaultRule:
    # 默认是否开启AI
    ai: false
    # 默认是否开启水群排行榜
    chatRank: false
    # 默认是否开启聊天记录总结
    summary: false
    # 默认是否开启新成员加群欢迎
    welcome: true
    # 每日早报
    news: false
# 微信HOOK配置
wechat:
  # 微信HOOK接口地址
  host: wechat:19088
  # 微信容器映射出来的vnc页面地址，没有就不填
  vncUrl: http://172.18.150.77:19087/vnc_lite.html
  # 是否在启动的时候自动设置hook服务的回调
  autoSetCallback: true
  # 回调IP，如果是Docker运行，本参数必填(填auto表示自动，不适用于 docker 环境)，如果Docker修改了映射，格式为 ip:port
  callback: auto
  # 转发到其他地址
  forward:
#    - 10.0.0.247:4299

# 数据库
mysql:
  drive: mysql # 使用的数据库驱动，支持 mysql、postgres
  host: mysql
  port: 3306
  user: 自己的用户
  password: 自己的密码
  db: wechat
  schema: public # postgres 专用

task:
  enable: true
  news:
    enable: true
    cron: "0 8 * * *" # 每天08:00
  syncFriends:
    enable: true
    cron: "*/10 * * * *" # 10分钟一次
  groupSummary:
    enable: true
    cron: "30 0 * * *" # 每天0:30
  goodMorning:
    enable: true
    cron: "30 5 * * *" # 每天0:30
  waterGroup:
    enable: true
    cron:
      yesterday: "30 8 * * *" # 每天8:30
      week: "40 2 * * 1" # 每周一8:30
      month: "35 2 1 * *" # 每月1号8:30
      year: "30 2 1 1 *" # 每年1月1号8:30

# MQ配置
mq:
  # 是否启用
  enable: false
  # RabbitMQ配置
  rabbitmq:
    host: 10.0.0.247
    port: 5672
    user: wechat
    password: wechat123
    vhost: wechat

# AI回复
ai:
  # 是否启用
  enable: true
  # 模型，不填默认gpt-3.5-turbo-0613
  model: gpt-4.0-mini
  # 群聊总结模型
  summaryModel: qwen-max
  # OpenAI Api key
  apiKey: 自己的 api key
  # 接口代理域名，不填默认ChatGPT官方地址
  baseUrl: 自己的 api 代理，可注释掉
  # 人设
  personality: 你的名字叫吼吼，吼吼的吼。
  models:
    - name: ChatGPT-4
      model: gpt-4-0613
    - name: 讯飞星火v3
      model: SparkDesk3
    - name: 讯飞星火随机
      model: SparkDesk
    - name: 月之暗面-8k
      model: moonshot-v1-8k
    - name: 月之暗面-32k
      model: moonshot-v1-32k
    - name: 月之暗面-128k
      model: moonshot-v1-128k
    - name: 跃问
      model: StepChat
    - name: 豆包Lite-4k
      model: Doubao-lite-4k
    - name: 豆包Pro-4k
      model: Doubao-pro-4k
# 资源配置
# map[k]v结构，k 会变成全小写，所以这儿不能用大写字母
resource:
  # 欢迎新成员表情包
  welcome-new:
    type: text
    path: 欢迎新人进群，妹子爆照，汉子发红包 -----群委会宣
  # 水群排行榜词云，只能是图片，末尾的`\%s`也是必须的
  wordcloud:
    type: image
    path: C:\users\app\Pictures\%s
  temp:
    path: C:\users\app\Downloads\%s
