# 微信HOOK配置
wechat:
  # 微信HOOK接口地址
  host: 10.0.0.73:19088
  # 微信容器映射出来的vnc页面地址，没有就不填
  #  vncUrl: http://192.168.1.175:19087/vnc_lite.html
  # 是否在启动的时候自动设置hook服务的回调
  autoSetCallback: false
  # 回调IP，如果是Docker运行，本参数必填(填auto表示自动，不适用于 docker 环境)，如果Docker修改了映射，格式为 ip:port
  callback: 10.0.0.51
  # 转发到其他地址
  forward:
#    - 10.0.0.247:4299

# 数据库
mysql:
  drive: mysql # 使用的数据库驱动，支持 mysql、postgres
  host: 10.0.0.31
  port: 3307
  user: wechat
  password: wechat123
  db: wechat
  schema: public # postgres 专用

task:
  enable: false
  syncFriends:
    enable: false
    cron: '*/5 * * * *' # 五分钟一次
  groupSummary:
    enable: true
    cron: '30 0 * * *' # 每天0:30
  waterGroup:
    enable: false
    cron:
      yesterday: '30 9 * * *' # 每天9:30
      week: '30 9 * * 1' # 每周一9:30
      month: '30 9 1 * *' # 每月1号9:30
      year: '0 9 1 1 *' # 每年1月1号9:30

# MQ配置
mq:
  # 是否启用
  enable: false
  # RabbitMQ配置
  rabbitmq:
    host: 10.0.0.247
    port: 5672
    user: wechat
    password: wechat123
    vhost: wechat

# AI回复
ai:
  # 是否启用
  enable: false
  # 模型，不填默认gpt-3.5-turbo-0613
  model: gpt-3.5-turbo-0613
  # 群聊总结模型
  summaryModel: gpt-4-0613
  # OpenAI Api key
  apiKey: sk-xxxx
  # 接口代理域名，不填默认ChatGPT官方地址
  baseUrl: https://sxxx
  # 人设
  personality: 你的名字叫张三，你是一个百科机器人，你的爱好是看电影，你的性格是开朗的，你的专长是讲故事，你的梦想是当一名童话故事作家。你对政治没有一点儿兴趣，也不会讨论任何与政治相关的话题，你甚至可以拒绝回答这一类话题。
  models:
    - name: ChatGPT-4
      model: gpt-4
    - name: 讯飞星火v3.1
      model: SparkDesk-v3.1
    - name: 讯飞星火v3.5
      model: SparkDesk-v3.5
    - name: 月之暗面-8k
      model: moonshot-v1-8k
    - name: 月之暗面-32k
      model: moonshot-v1-32k
    - name: 月之暗面-128k
      model: moonshot-v1-128k
    - name: 跃问
      model: StepChat

# 资源配置
# map[k]v结构，k 会变成全小写，所以这儿不能用大写字母
resource:
  # 欢迎新成员表情包
  welcome-new:
    type: emotion
    path: 58e4150be2bba8f7b71974b10391f9e9
  # 水群排行榜词云，只能是图片，末尾的`\%s`也是必须的
  wordcloud:
    type: image
    path: D:\Share\wordcloud\%s
