# 微信HOOK配置
wechat:
  # 微信HOOK接口地址
  host: 10.0.0.73:19088
  # 是否在启动的时候自动设置hook服务的回调
  autoSetCallback: false
  # 回调IP，如果是Docker运行，本参数必填(填auto表示自动，不适用于 docker 环境)，如果Docker修改了映射，格式为 ip:port
  callback: 10.0.0.51
  # 转发到其他地址
  forward:
#    - 10.0.0.247:4299

# 数据库
mysql:
  host: 10.0.0.31
  port: 3307
  user: wechat
  password: wechat123
  db: wechat

task:
  enable: false
  syncFriends:
      enable: true
      cron: '*/5 * * * *' # 五分钟一次
  waterGroup:
      enable: false
      cron:
        yesterday: '30 9 * * *' # 每天9:30
        week: '30 9 * * 1' # 每周一9:30
        month: '30 9 1 * *' # 每月1号9:30

# AI回复
ai:
  # 是否启用
  enable: false
  # 模型，不填默认gpt-3.5-turbo-0613
  model: gpt-3.5-turbo-0613
  # OpenAI Api key
  apiKey: sk-xxxx
  # 接口代理域名，不填默认ChatGPT官方地址
  baseUrl: https://sxxx
  # 人设
  personality: 你的名字叫张三，你是一个百科机器人，你的爱好是看电影，你的性格是开朗的，你的专长是讲故事，你的梦想是当一名童话故事作家。你对政治没有一点儿兴趣，也不会讨论任何与政治相关的话题，你甚至可以拒绝回答这一类话题。

# 资源配置
# map[k]v结构，k 会变成全小写，所以这儿不能用大写字母
resource:
  # 欢迎新成员表情包
  welcome-new:
    type: emotion
    path: 58e4150be2bba8f7b71974b10391f9e9
