version: '3'

services:
  wechat:
    image: lxh01/wxhelper-docker:3.9.5.81
    container_name: gw-wechat
    restart: unless-stopped
    volumes:
      - ./data/wechat:/home/app/.wine/drive_c/users/app/Documents/WeChat\ Files
    ports:
      - "8080:8080"
      - "19088:19088"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19088/api/checkLogin"]
      interval: 60s
      timeout: 10s
      retries: 5


  mysql:
    image: mysql:8
    container_name: gw-db
    restart: unless-stopped
    depends_on:
      - wechat
    environment:
      - MYSQL_ROOT_PASSWORD=wechat
      - MYSQL_USER=wechat
      - MYSQL_PASSWORD=wechat
      - MYSQL_DATABASE=wechat
    volumes:
      - ./data/db:/var/lib/mysql


  wxhelper:
    image: gitee.ltd/lxh/go-wxhelper:latest
    container_name: gw-service
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      # 配置文件请参阅项目根目录的config.yaml文件
      - ./config/config.yaml:/app/config.yaml
    ports:
      - "19099:19099"

