name: BuildImage

on:
  push:
    branches:
      - main
#      - '*'
#      - '!main'

jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      # 使用这个镜像，不然Docker无法打包镜像
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'
          cache: false

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Gen Tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["gitee.ltd/lxh/go-wxhelper:latest","gitee.ltd/lxh/go-wxhelper:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["gitee.ltd/lxh/go-wxhelper:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: Login to Repository
        uses: docker/login-action@v2
        with:
          registry: gitee.ltd
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
